name: firebase_crud
description: "A Flutter Firebase CRUD project with Email Authentication, Google Sign-In, and Cloud Firestore."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.15.2
  firebase_auth: ^5.6.3
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/