// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkBYhvQI9uz0oYlFVMre-yX5a5MpyLBg',
    appId: '1:347336235922:web:58feeafa5311bba85f3f4b',
    messagingSenderId: '347336235922',
    projectId: 'notes-1912a',
    authDomain: 'notes-1912a.firebaseapp.com',
    storageBucket: 'notes-1912a.firebasestorage.app',
    measurementId: 'G-Y68SBQPH24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC87GJbMHIKbmV7XnTDOrj2jAvxkXrVqwI',
    appId: '1:347336235922:android:050a45a425fa5c1c5f3f4b',
    messagingSenderId: '347336235922',
    projectId: 'notes-1912a',
    storageBucket: 'notes-1912a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9YEgkYaD7tjbYf0vbVZqiKJLxa9pzmVQ',
    appId: '1:347336235922:ios:192d7d716e3d5da65f3f4b',
    messagingSenderId: '347336235922',
    projectId: 'notes-1912a',
    storageBucket: 'notes-1912a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
